services:
  # Customers service
  customers:
    build:
      context: .
      args:
        - SERVICE_PATH=customers
        - PACKAGE_NAME=customers
        - PNPM_VERSION=9.15.0
    ports:
      - 5555:5555
    environment:
      - NODE_ENV=production
      - CUSTOMERS_MONGO_URL=mongodb://mongo-customers:27017/customers
    depends_on:
      - mongo-customers
    networks:
      - canigetta-network

  # ==== Customers db ====
  mongo-customers:
    container_name: customers-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-customers-data:/data/db
    networks:
      - canigetta-network

  # ================================
  # Inventory service
  inventory:
    build:
      context: .
      args:
        - SERVICE_PATH=inventory
        - PACKAGE_NAME=inventory
        - PNPM_VERSION=9.15.0
    ports:
      - 4545:4545
    environment:
      - NODE_ENV=production
      - INVENTORY_MONGO_URL=mongodb://mongo-inventory:27017/inventory
    networks:
      - canigetta-network

  # ==== Inventory db ====
  mongo-inventory:
    container_name: inventory-db
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo-inventory-data:/data/db
    networks:
      - canigetta-network

  # ================================
  # Orders service
  orders:
    build:
      context: .
      args:
        - SERVICE_PATH=orders
        - PACKAGE_NAME=orders
        - PNPM_VERSION=9.15.0
    ports:
      - 7777:7777
    environment:
      - NODE_ENV=production
      - ORDERS_MONGO_URL=mongodb://mongo-orders:27017/orders
    networks:
      - canigetta-network

  # ==== Orders db ====
  mongo-orders:
    container_name: orders-db
    image: mongo:latest
    ports:
      - 27019:27017
    volumes:
      - mongo-orders-data:/data/db
    networks:
      - canigetta-network

  # ===== nginx proxy =====
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orders
      - inventory
      - customers
    networks:
      - canigetta-network

networks:
  canigetta-network:
    driver: bridge

volumes:
  mongo-customers-data:
  mongo-inventory-data:
  mongo-orders-data:
