FROM node:18.20.4-slim

WORKDIR /app

COPY pnpm-lock.yaml package.json ./

RUN npm install -g pnpm@9.15.0 && pnpm install --frozen-lockfile

COPY . .

EXPOSE 5555

WORKDIR /app/customers

CMD ["pnpm", "dev"]